#!/bin/sh
#
# This hook is called by "git commit" to prepare 
# the commit log message.
#
# below we intercept the hook to intentionally slow 
# down git's application of cherry-picks during rebase
# todos that can cause collision with a persistent
# .git/index.lock file on slower releasing EFS filesystems.
#
# 1) pause for 5s,
# 2) if .git/index.lock persists ... delete it
#
# To enable this hook, rename this file to "prepare-commit-msg"
# To disable this hook, rename this file to "prepare-commit-msg.sample"
# author: Stu Field

FILE=$GIT_DIR/index.lock

echo "* prepare-commit-msg hook ..."
echo "\tpausing for 5s ..."
sleep 5.0

if [ -f $FILE ]; then
  echo "\tdeleting '$FILE' file ..."
  rm -f $FILE
fi
